<?xml version="1.0" encoding="utf-8"?><Database Name="DocumentManagement" Class="LinqToSqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-HB1MM1S\SQLEXPRESS;Initial Catalog=DocumentManagement;Persist Security Info=True;User ID=sa" SettingsObjectName="Record.Properties.Settings" SettingsPropertyName="DocumentManagementConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DocumentTable" Member="DocumentTables">
    <Type Name="DocumentTable">
      <Column Name="doc_id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="doc_type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="scan_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="filing_path" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="file_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="checkin_time" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="checkout_time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="doc_name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="size" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="total_share_in_group" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total_share_individual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GroupTable" Member="GroupTables">
    <Type Name="GroupTable">
      <Column Name="group_id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="group_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="admin_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="total_member" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total_document" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserTable" Member="UserTables">
    <Type Name="UserTable">
      <Column Name="user_id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="no_of_document" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="department" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_image_path" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="no_of_group" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>