<?xml version="1.0" encoding="utf-8"?><Database Name="DocumentManagement" Class="LinqToSql2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-HB1MM1S\SQLEXPRESS;Initial Catalog=DocumentManagement;User ID=sa" SettingsObjectName="Record.Properties.Settings" SettingsPropertyName="DocumentManagementConnectionString4" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DocumentAndGroupTable" Member="DocumentAndGroupTables">
    <Type Name="DocumentAndGroupTable">
      <Column Name="doc_group_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="doc_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="group_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="doc_right" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserAndDocumentTable" Member="UserAndDocumentTables">
    <Type Name="UserAndDocumentTable">
      <Column Name="user_doc_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="doc_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="doc_right" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserAndGroupTable" Member="UserAndGroupTables">
    <Type Name="UserAndGroupTable">
      <Column Name="user_group_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="group_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>