//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Record.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HB1MM1S\\SQLEXPRESS;Initial Catalog=\"Document and Record Manag" +
            "ement\";Persist Security Info=True;User ID=sa;Password=zxcvbnm")]
        public string Document_and_Record_ManagementConnectionString {
            get {
                return ((string)(this["Document_and_Record_ManagementConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-B9434U2;Initial Catalog=DocumentManagement;Persist Security I" +
            "nfo=True;User ID=sa;Password=najrulislam")]
        public string DocumentManagementConnectionString {
            get {
                return ((string)(this["DocumentManagementConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-B9434U2;Initial Catalog=DocumentManagement;Integrated Securit" +
            "y=True")]
        public string DocumentManagementConnectionString1 {
            get {
                return ((string)(this["DocumentManagementConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HB1MM1S\\SQLEXPRESS;Initial Catalog=DocumentManagement;Integra" +
            "ted Security=True")]
        public string DocumentManagementConnectionString2 {
            get {
                return ((string)(this["DocumentManagementConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HB1MM1S\\SQLEXPRESS;Initial Catalog=DocumentManagement;Persist" +
            " Security Info=True;User ID=sa;Password=zxcvbnm")]
        public string DocumentManagementConnectionString3 {
            get {
                return ((string)(this["DocumentManagementConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HB1MM1S\\SQLEXPRESS;Initial Catalog=DocumentManagement;User ID" +
            "=sa;Password=zxcvbnm")]
        public string DocumentManagementConnectionString4 {
            get {
                return ((string)(this["DocumentManagementConnectionString4"]));
            }
        }
    }
}
